
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.MediaScalarFieldEnum = {
  id: 'id',
  assetType: 'assetType',
  assetKey: 'assetKey',
  derivedFromId: 'derivedFromId',
  filename: 'filename',
  originalName: 'originalName',
  mimeType: 'mimeType',
  extension: 'extension',
  size: 'size',
  fileHash: 'fileHash',
  width: 'width',
  height: 'height',
  duration: 'duration',
  aspectRatio: 'aspectRatio',
  storageProvider: 'storageProvider',
  path: 'path',
  publicUrl: 'publicUrl',
  alt: 'alt',
  caption: 'caption',
  dominantColor: 'dominantColor',
  blurHash: 'blurHash',
  uploadedById: 'uploadedById',
  focusX: 'focusX',
  focusY: 'focusY',
  visibility: 'visibility',
  status: 'status',
  usageCount: 'usageCount',
  aiCaption: 'aiCaption',
  aiTags: 'aiTags',
  ocrText: 'ocrText',
  labels: 'labels',
  scene: 'scene',
  objects: 'objects',
  faces: 'faces',
  brand: 'brand',
  keywords: 'keywords',
  nsfwScore: 'nsfwScore',
  qualityScore: 'qualityScore',
  colorPalette: 'colorPalette',
  embeddingVector: 'embeddingVector',
  similarityHash: 'similarityHash',
  folderId: 'folderId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.MediaFolderScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MediaCollectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MediaCollectionMappingScalarFieldEnum = {
  mediaId: 'mediaId',
  collectionId: 'collectionId',
  createdAt: 'createdAt'
};

exports.Prisma.MediaVersionScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  versionNumber: 'versionNumber',
  fileName: 'fileName',
  storagePath: 'storagePath',
  publicUrl: 'publicUrl',
  fileHash: 'fileHash',
  size: 'size',
  mimeType: 'mimeType',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.MediaVariantScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  variantName: 'variantName',
  width: 'width',
  height: 'height',
  size: 'size',
  mimeType: 'mimeType',
  storagePath: 'storagePath',
  publicUrl: 'publicUrl',
  createdAt: 'createdAt'
};

exports.Prisma.MediaTagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt'
};

exports.Prisma.MediaTagMappingScalarFieldEnum = {
  mediaId: 'mediaId',
  tagId: 'tagId',
  createdAt: 'createdAt'
};

exports.Prisma.MediaUsageScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  entityType: 'entityType',
  entityId: 'entityId',
  field: 'field',
  createdAt: 'createdAt'
};

exports.Prisma.AssetMetadataScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  key: 'key',
  value: 'value',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  dob: 'dob',
  gender: 'gender',
  avatarId: 'avatarId',
  language: 'language',
  currency: 'currency',
  theme: 'theme',
  savedPreferences: 'savedPreferences',
  notificationPrefs: 'notificationPrefs',
  role: 'role',
  status: 'status',
  failedLoginAttempts: 'failedLoginAttempts',
  lockedUntil: 'lockedUntil',
  emailVerifiedAt: 'emailVerifiedAt',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.UserSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  deviceName: 'deviceName',
  browser: 'browser',
  browserVersion: 'browserVersion',
  os: 'os',
  ip: 'ip',
  country: 'country',
  city: 'city',
  userAgent: 'userAgent',
  expiresAt: 'expiresAt',
  lastActivity: 'lastActivity',
  revokedAt: 'revokedAt',
  createdAt: 'createdAt'
};

exports.Prisma.TokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  hash: 'hash',
  attempts: 'attempts',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.AddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  phone: 'phone',
  company: 'company',
  label: 'label',
  street: 'street',
  landmark: 'landmark',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  country: 'country',
  addressType: 'addressType',
  deliveryInstructions: 'deliveryInstructions',
  isBilling: 'isBilling',
  isShipping: 'isShipping',
  isDefault: 'isDefault',
  latitude: 'latitude',
  longitude: 'longitude',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  parentId: 'parentId',
  iconMediaId: 'iconMediaId',
  bannerMediaId: 'bannerMediaId',
  thumbnailMediaId: 'thumbnailMediaId',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  mediaId: 'mediaId',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  isAutomatic: 'isAutomatic',
  rules: 'rules',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollectionProductScalarFieldEnum = {
  collectionId: 'collectionId',
  productId: 'productId',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  categoryId: 'categoryId',
  name: 'name',
  slug: 'slug',
  shortDescription: 'shortDescription',
  longDescription: 'longDescription',
  status: 'status',
  visibility: 'visibility',
  ratingAverage: 'ratingAverage',
  reviewCount: 'reviewCount',
  viewCount: 'viewCount',
  salesCount: 'salesCount',
  wishlistCount: 'wishlistCount',
  favoriteCount: 'favoriteCount',
  hsnCode: 'hsnCode',
  gstRate: 'gstRate',
  taxClass: 'taxClass',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.ProductSlugHistoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  oldSlug: 'oldSlug',
  newSlug: 'newSlug',
  redirect: 'redirect',
  createdAt: 'createdAt'
};

exports.Prisma.ProductSeoScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  keywords: 'keywords',
  ogImageId: 'ogImageId',
  createdAt: 'createdAt'
};

exports.Prisma.CategorySeoScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  ogImageId: 'ogImageId'
};

exports.Prisma.BrandSeoScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  ogImageId: 'ogImageId'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt'
};

exports.Prisma.ProductTagScalarFieldEnum = {
  productId: 'productId',
  tagId: 'tagId'
};

exports.Prisma.ProductImageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  mediaId: 'mediaId',
  isPrimary: 'isPrimary',
  sortOrder: 'sortOrder',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.AttributeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  isFilterable: 'isFilterable',
  createdAt: 'createdAt'
};

exports.Prisma.AttributeValueScalarFieldEnum = {
  id: 'id',
  attributeId: 'attributeId',
  value: 'value',
  meta: 'meta',
  sortOrder: 'sortOrder'
};

exports.Prisma.ProductAttributeScalarFieldEnum = {
  productId: 'productId',
  attributeId: 'attributeId'
};

exports.Prisma.ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  sku: 'sku',
  barcode: 'barcode',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.ProductPriceScalarFieldEnum = {
  id: 'id',
  productVariantId: 'productVariantId',
  mrp: 'mrp',
  sellingPrice: 'sellingPrice',
  costPrice: 'costPrice',
  currency: 'currency',
  tax: 'tax',
  effectiveFrom: 'effectiveFrom',
  effectiveTo: 'effectiveTo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VariantAttributeScalarFieldEnum = {
  variantId: 'variantId',
  attributeValueId: 'attributeValueId'
};

exports.Prisma.SpecificationGroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.SpecificationScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.ProductSpecificationScalarFieldEnum = {
  productId: 'productId',
  specId: 'specId',
  value: 'value'
};

exports.Prisma.InventoryScalarFieldEnum = {
  id: 'id',
  variantId: 'variantId',
  quantityAvailable: 'quantityAvailable',
  quantityReserved: 'quantityReserved',
  lowStockThreshold: 'lowStockThreshold',
  status: 'status',
  warehouseId: 'warehouseId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryMovementScalarFieldEnum = {
  id: 'id',
  inventoryId: 'inventoryId',
  quantity: 'quantity',
  type: 'type',
  referenceId: 'referenceId',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CartItemScalarFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  variantId: 'variantId',
  quantity: 'quantity',
  isSaved: 'isSaved',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WishlistScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WishlistItemScalarFieldEnum = {
  id: 'id',
  wishlistId: 'wishlistId',
  productId: 'productId',
  createdAt: 'createdAt'
};

exports.Prisma.ShippingProviderScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShippingZoneScalarFieldEnum = {
  id: 'id',
  shippingProviderId: 'shippingProviderId',
  name: 'name',
  countries: 'countries',
  isActive: 'isActive'
};

exports.Prisma.ShippingRateScalarFieldEnum = {
  id: 'id',
  zoneId: 'zoneId',
  methodName: 'methodName',
  cost: 'cost',
  minOrder: 'minOrder',
  maxOrder: 'maxOrder',
  estDays: 'estDays',
  isActive: 'isActive'
};

exports.Prisma.CheckoutSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  cartId: 'cartId',
  shippingAddress: 'shippingAddress',
  billingAddress: 'billingAddress',
  couponCode: 'couponCode',
  shippingMethod: 'shippingMethod',
  subTotal: 'subTotal',
  taxTotal: 'taxTotal',
  shippingTotal: 'shippingTotal',
  discountTotal: 'discountTotal',
  grandTotal: 'grandTotal',
  paymentMethodCode: 'paymentMethodCode',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  userId: 'userId',
  checkoutSessionId: 'checkoutSessionId',
  subTotal: 'subTotal',
  discountTotal: 'discountTotal',
  taxTotal: 'taxTotal',
  shippingTotal: 'shippingTotal',
  grandTotal: 'grandTotal',
  status: 'status',
  shippingName: 'shippingName',
  shippingPhone: 'shippingPhone',
  shippingEmail: 'shippingEmail',
  shippingStreet: 'shippingStreet',
  shippingCity: 'shippingCity',
  shippingState: 'shippingState',
  shippingCountry: 'shippingCountry',
  shippingPostalCode: 'shippingPostalCode',
  billingAddr: 'billingAddr',
  cgstDecimal: 'cgstDecimal',
  sgstDecimal: 'sgstDecimal',
  igstDecimal: 'igstDecimal',
  utgstDecimal: 'utgstDecimal',
  gstin: 'gstin',
  companyName: 'companyName',
  invoiceType: 'invoiceType',
  isBusinessOrder: 'isBusinessOrder',
  couponCode: 'couponCode',
  discountType: 'discountType',
  discountValue: 'discountValue',
  couponDiscount: 'couponDiscount',
  shippingProvider: 'shippingProvider',
  trackingNumber: 'trackingNumber',
  estimatedDelivery: 'estimatedDelivery',
  shippingCost: 'shippingCost',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderTimelineScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  status: 'status',
  message: 'message',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  variantId: 'variantId',
  productName: 'productName',
  brandName: 'brandName',
  sku: 'sku',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discount: 'discount',
  tax: 'tax',
  totalPrice: 'totalPrice',
  createdAt: 'createdAt'
};

exports.Prisma.ReturnScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  reason: 'reason',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReturnItemScalarFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  orderItemId: 'orderItemId',
  quantity: 'quantity'
};

exports.Prisma.RefundScalarFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  paymentId: 'paymentId',
  amount: 'amount',
  status: 'status',
  reason: 'reason',
  providerRefundId: 'providerRefundId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CouponScalarFieldEnum = {
  id: 'id',
  code: 'code',
  discountType: 'discountType',
  discountValue: 'discountValue',
  minOrderAmount: 'minOrderAmount',
  maxUses: 'maxUses',
  usagePerCustomer: 'usagePerCustomer',
  usedCount: 'usedCount',
  categoryRestrictions: 'categoryRestrictions',
  productRestrictions: 'productRestrictions',
  excludedProducts: 'excludedProducts',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.CouponRuleScalarFieldEnum = {
  id: 'id',
  couponId: 'couponId',
  type: 'type',
  value: 'value',
  createdAt: 'createdAt'
};

exports.Prisma.CouponConditionScalarFieldEnum = {
  id: 'id',
  ruleId: 'ruleId',
  field: 'field',
  operator: 'operator',
  value: 'value',
  createdAt: 'createdAt'
};

exports.Prisma.CouponUsageScalarFieldEnum = {
  id: 'id',
  couponId: 'couponId',
  userId: 'userId',
  orderId: 'orderId',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  amount: 'amount',
  currency: 'currency',
  paymentMethodCode: 'paymentMethodCode',
  provider: 'provider',
  providerPaymentId: 'providerPaymentId',
  providerOrderId: 'providerOrderId',
  status: 'status',
  failureReason: 'failureReason',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentMethodScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  type: 'type',
  description: 'description',
  isActive: 'isActive',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentProviderScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentMethodProviderScalarFieldEnum = {
  id: 'id',
  paymentMethodId: 'paymentMethodId',
  providerId: 'providerId',
  priority: 'priority',
  enabled: 'enabled',
  config: 'config',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentProviderConfigScalarFieldEnum = {
  id: 'id',
  providerId: 'providerId',
  environment: 'environment',
  key: 'key',
  encryptedSecret: 'encryptedSecret',
  webhookSecret: 'webhookSecret',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentMethodRuleScalarFieldEnum = {
  id: 'id',
  paymentMethodId: 'paymentMethodId',
  minAmount: 'minAmount',
  maxAmount: 'maxAmount',
  allowedPincodes: 'allowedPincodes',
  blockedPincodes: 'blockedPincodes',
  allowedCategories: 'allowedCategories',
  blockedCategories: 'blockedCategories',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentEventScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  status: 'status',
  providerPaymentId: 'providerPaymentId',
  rawPayload: 'rawPayload',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentAttemptScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  providerPaymentId: 'providerPaymentId',
  status: 'status',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentWebhookScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  provider: 'provider',
  eventId: 'eventId',
  eventType: 'eventType',
  rawPayload: 'rawPayload',
  signature: 'signature',
  processed: 'processed',
  receivedAt: 'receivedAt'
};

exports.Prisma.PaymentAuditScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  action: 'action',
  previousStatus: 'previousStatus',
  newStatus: 'newStatus',
  providerResponse: 'providerResponse',
  createdAt: 'createdAt'
};

exports.Prisma.TaxRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  rate: 'rate',
  country: 'country',
  state: 'state',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  userId: 'userId',
  rating: 'rating',
  title: 'title',
  comment: 'comment',
  isVerified: 'isVerified',
  helpfulVotes: 'helpfulVotes',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  type: 'type',
  category: 'category',
  channel: 'channel',
  priority: 'priority',
  recipientId: 'recipientId',
  recipientContact: 'recipientContact',
  status: 'status',
  templateId: 'templateId',
  payload: 'payload',
  title: 'title',
  body: 'body',
  isRead: 'isRead',
  scheduledAt: 'scheduledAt',
  sentAt: 'sentAt',
  readAt: 'readAt',
  failedAt: 'failedAt',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationActionScalarFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  label: 'label',
  url: 'url',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationJobScalarFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  attempts: 'attempts',
  maxRetries: 'maxRetries',
  lastError: 'lastError',
  nextAttemptAt: 'nextAttemptAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationLogScalarFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  recipient: 'recipient',
  provider: 'provider',
  channel: 'channel',
  templateId: 'templateId',
  latencyMs: 'latencyMs',
  status: 'status',
  response: 'response',
  retries: 'retries',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationTemplateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  name: 'name',
  event: 'event',
  channel: 'channel',
  category: 'category',
  subject: 'subject',
  html: 'html',
  text: 'text',
  variables: 'variables',
  currentVersion: 'currentVersion',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationTemplateVersionScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  version: 'version',
  subject: 'subject',
  html: 'html',
  text: 'text',
  variables: 'variables',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationSettingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  category: 'category',
  channel: 'channel',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PushDeviceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  deviceToken: 'deviceToken',
  platform: 'platform',
  browser: 'browser',
  lastActiveAt: 'lastActiveAt',
  createdAt: 'createdAt'
};

exports.Prisma.WebhookSubscriptionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  targetUrl: 'targetUrl',
  secret: 'secret',
  events: 'events',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SearchHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  query: 'query',
  resultCount: 'resultCount',
  clickedProductId: 'clickedProductId',
  createdAt: 'createdAt'
};

exports.Prisma.PopularSearchScalarFieldEnum = {
  id: 'id',
  query: 'query',
  searchCount: 'searchCount',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecentlyViewedScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  viewedAt: 'viewedAt'
};

exports.Prisma.SettingScalarFieldEnum = {
  key: 'key',
  value: 'value',
  description: 'description',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  action: 'action',
  changes: 'changes',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebsiteScalarFieldEnum = {
  id: 'id',
  domain: 'domain',
  name: 'name',
  isActive: 'isActive',
  organizationId: 'organizationId',
  activeVersionId: 'activeVersionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebsiteSettingsScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  brandName: 'brandName',
  websiteName: 'websiteName',
  logoUrl: 'logoUrl',
  faviconUrl: 'faviconUrl',
  tagline: 'tagline',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  businessAddress: 'businessAddress',
  defaultCurrency: 'defaultCurrency',
  defaultLanguage: 'defaultLanguage',
  searchPlaceholder: 'searchPlaceholder',
  copyright: 'copyright',
  socialLinksJson: 'socialLinksJson',
  supportEmail: 'supportEmail',
  supportPhone: 'supportPhone',
  announcementsJson: 'announcementsJson',
  trendingSearchesJson: 'trendingSearchesJson',
  paymentBadgesJson: 'paymentBadgesJson',
  megaMenuFeaturedJson: 'megaMenuFeaturedJson',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebsiteDraftScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  name: 'name',
  version: 'version',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebsiteVersionScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  versionLabel: 'versionLabel',
  payload: 'payload',
  hash: 'hash',
  isLive: 'isLive',
  publishedAt: 'publishedAt'
};

exports.Prisma.WebsiteThemeScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.ThemeTokenScalarFieldEnum = {
  id: 'id',
  themeId: 'themeId',
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebsiteLayoutScalarFieldEnum = {
  id: 'id',
  themeId: 'themeId',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WebsitePageScalarFieldEnum = {
  id: 'id',
  layoutId: 'layoutId',
  title: 'title',
  slug: 'slug',
  isPublished: 'isPublished',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PageRouteScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  routePath: 'routePath',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SeoScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  robots: 'robots',
  schemaJson: 'schemaJson',
  twitterCard: 'twitterCard',
  ogImageId: 'ogImageId',
  faviconId: 'faviconId'
};

exports.Prisma.ComponentRegistryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  schema: 'schema',
  version: 'version',
  createdAt: 'createdAt'
};

exports.Prisma.WebsiteSectionScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  name: 'name',
  sortOrder: 'sortOrder'
};

exports.Prisma.WebsiteComponentScalarFieldEnum = {
  id: 'id',
  sectionId: 'sectionId',
  registryId: 'registryId',
  sortOrder: 'sortOrder'
};

exports.Prisma.WebsiteComponentPropertyScalarFieldEnum = {
  id: 'id',
  componentId: 'componentId',
  key: 'key',
  bindingType: 'bindingType',
  literalValue: 'literalValue',
  entityType: 'entityType',
  entityId: 'entityId',
  expression: 'expression',
  schemaType: 'schemaType'
};

exports.Prisma.WebsiteNavigationScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  handle: 'handle',
  name: 'name',
  type: 'type'
};

exports.Prisma.WebsiteMenuScalarFieldEnum = {
  id: 'id',
  navigationId: 'navigationId',
  label: 'label',
  url: 'url',
  parentId: 'parentId',
  sortOrder: 'sortOrder'
};

exports.Prisma.WebsiteAIConfigScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  assistantName: 'assistantName',
  avatarUrl: 'avatarUrl',
  greeting: 'greeting',
  suggestionsJson: 'suggestionsJson',
  prompt: 'prompt',
  model: 'model',
  temperature: 'temperature',
  tone: 'tone',
  enableSearch: 'enableSearch',
  enableCompare: 'enableCompare',
  enableRecommendations: 'enableRecommendations',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScriptInjectionScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  name: 'name',
  placement: 'placement',
  code: 'code',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MediaReferenceScalarFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  mediaId: 'mediaId',
  createdAt: 'createdAt'
};

exports.Prisma.WebsiteBannerScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  name: 'name',
  linkUrl: 'linkUrl',
  position: 'position',
  isActive: 'isActive',
  sortOrder: 'sortOrder'
};

exports.Prisma.AnalyticsEventScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  userId: 'userId',
  sessionId: 'sessionId',
  event: 'event',
  category: 'category',
  entityType: 'entityType',
  entityId: 'entityId',
  properties: 'properties',
  ipAddress: 'ipAddress',
  country: 'country',
  city: 'city',
  device: 'device',
  browser: 'browser',
  platform: 'platform',
  referrer: 'referrer',
  utmSource: 'utmSource',
  utmMedium: 'utmMedium',
  utmCampaign: 'utmCampaign',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  visitorId: 'visitorId',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  pageViews: 'pageViews',
  duration: 'duration',
  device: 'device',
  browser: 'browser',
  os: 'os',
  country: 'country',
  city: 'city',
  entryPage: 'entryPage',
  exitPage: 'exitPage',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsPageViewScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  page: 'page',
  title: 'title',
  duration: 'duration',
  referrer: 'referrer',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsHeatmapScalarFieldEnum = {
  id: 'id',
  page: 'page',
  x: 'x',
  y: 'y',
  clickCount: 'clickCount',
  createdAt: 'createdAt'
};

exports.Prisma.CustomerAnalyticsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  totalOrders: 'totalOrders',
  totalRevenue: 'totalRevenue',
  averageOrderValue: 'averageOrderValue',
  lifetimeValue: 'lifetimeValue',
  firstPurchaseAt: 'firstPurchaseAt',
  lastPurchaseAt: 'lastPurchaseAt',
  daysSinceLastPurchase: 'daysSinceLastPurchase',
  refundCount: 'refundCount',
  wishlistCount: 'wishlistCount',
  reviewCount: 'reviewCount',
  favoriteCategory: 'favoriteCategory',
  favoriteBrand: 'favoriteBrand',
  customerSegment: 'customerSegment',
  predictedChurnScore: 'predictedChurnScore',
  predictedLtv: 'predictedLtv',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CampaignMetricsScalarFieldEnum = {
  id: 'id',
  campaign: 'campaign',
  sessions: 'sessions',
  orders: 'orders',
  revenue: 'revenue',
  conversionRate: 'conversionRate',
  cost: 'cost',
  roas: 'roas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureUsageMetricsScalarFieldEnum = {
  id: 'id',
  feature: 'feature',
  count: 'count',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnalyticsProductMetricsScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  date: 'date',
  views: 'views',
  wishlistAdds: 'wishlistAdds',
  cartAdds: 'cartAdds',
  purchases: 'purchases',
  returns: 'returns',
  revenue: 'revenue',
  conversionRate: 'conversionRate',
  embeddingReady: 'embeddingReady',
  summaryReady: 'summaryReady',
  anomalyScore: 'anomalyScore',
  forecastReady: 'forecastReady',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsCategoryMetricsScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  date: 'date',
  views: 'views',
  revenue: 'revenue',
  orders: 'orders',
  conversionRate: 'conversionRate',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsSalesMetricsScalarFieldEnum = {
  id: 'id',
  date: 'date',
  orders: 'orders',
  customers: 'customers',
  revenue: 'revenue',
  refunds: 'refunds',
  aov: 'aov',
  netRevenue: 'netRevenue',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsTrafficMetricsScalarFieldEnum = {
  id: 'id',
  date: 'date',
  sessions: 'sessions',
  users: 'users',
  bounceRate: 'bounceRate',
  avgDuration: 'avgDuration',
  newUsers: 'newUsers',
  returningUsers: 'returningUsers',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsSearchMetricsScalarFieldEnum = {
  id: 'id',
  query: 'query',
  count: 'count',
  resultsClicked: 'resultsClicked',
  conversionRate: 'conversionRate',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsFunnelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsFunnelStepScalarFieldEnum = {
  id: 'id',
  funnelId: 'funnelId',
  name: 'name',
  event: 'event',
  sortOrder: 'sortOrder'
};

exports.Prisma.DashboardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isDefault: 'isDefault',
  createdAt: 'createdAt'
};

exports.Prisma.DashboardWidgetScalarFieldEnum = {
  id: 'id',
  dashboardId: 'dashboardId',
  title: 'title',
  type: 'type',
  metric: 'metric',
  width: 'width',
  height: 'height',
  sortOrder: 'sortOrder'
};

exports.Prisma.DashboardLayoutScalarFieldEnum = {
  id: 'id',
  widgetId: 'widgetId',
  userId: 'userId',
  x: 'x',
  y: 'y',
  w: 'w',
  h: 'h'
};

exports.Prisma.ForecastDatasetScalarFieldEnum = {
  id: 'id',
  metric: 'metric',
  date: 'date',
  value: 'value',
  granularity: 'granularity',
  createdAt: 'createdAt'
};

exports.Prisma.AlertRuleScalarFieldEnum = {
  id: 'id',
  metric: 'metric',
  operator: 'operator',
  threshold: 'threshold',
  severity: 'severity',
  enabled: 'enabled',
  createdAt: 'createdAt'
};

exports.Prisma.ScheduledReportScalarFieldEnum = {
  id: 'id',
  name: 'name',
  frequency: 'frequency',
  recipients: 'recipients',
  format: 'format',
  timezone: 'timezone',
  lastSentAt: 'lastSentAt',
  createdAt: 'createdAt'
};

exports.Prisma.AnalyticsDashboardCacheScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.AIProviderScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIModelScalarFieldEnum = {
  id: 'id',
  providerId: 'providerId',
  code: 'code',
  name: 'name',
  inputCostRate: 'inputCostRate',
  outputCostRate: 'outputCostRate',
  contextWindow: 'contextWindow',
  createdAt: 'createdAt'
};

exports.Prisma.AIConfigurationScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  defaultProvider: 'defaultProvider',
  defaultModel: 'defaultModel',
  temperature: 'temperature',
  maxTokens: 'maxTokens',
  enabledFeatures: 'enabledFeatures',
  monthlyBudget: 'monthlyBudget',
  dailyBudget: 'dailyBudget',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIConversationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content',
  tokens: 'tokens',
  latencyMs: 'latencyMs',
  cost: 'cost',
  createdAt: 'createdAt'
};

exports.Prisma.AIJobScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  payload: 'payload',
  result: 'result',
  error: 'error',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIUsageScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  feature: 'feature',
  provider: 'provider',
  model: 'model',
  promptTokens: 'promptTokens',
  completionTokens: 'completionTokens',
  cost: 'cost',
  latencyMs: 'latencyMs',
  createdAt: 'createdAt'
};

exports.Prisma.AIPromptTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  systemInstruction: 'systemInstruction',
  userPromptSchema: 'userPromptSchema',
  variables: 'variables',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIEmbeddingScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  vector: 'vector',
  createdAt: 'createdAt'
};

exports.Prisma.CountryScalarFieldEnum = {
  code: 'code',
  name: 'name',
  currency: 'currency',
  currencySymbol: 'currencySymbol',
  locale: 'locale',
  phonePrefix: 'phonePrefix',
  phoneLength: 'phoneLength',
  isActive: 'isActive'
};

exports.Prisma.StateScalarFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  code: 'code',
  name: 'name',
  isUnionTerritory: 'isUnionTerritory'
};

exports.Prisma.DistrictScalarFieldEnum = {
  id: 'id',
  stateId: 'stateId',
  name: 'name'
};

exports.Prisma.CityScalarFieldEnum = {
  id: 'id',
  districtId: 'districtId',
  name: 'name'
};

exports.Prisma.PincodeScalarFieldEnum = {
  code: 'code',
  cityId: 'cityId',
  stateId: 'stateId',
  isServiced: 'isServiced',
  isCOD: 'isCOD',
  isExpress: 'isExpress',
  estDaysMin: 'estDaysMin',
  estDaysMax: 'estDaysMax',
  shippingCharge: 'shippingCharge'
};

exports.Prisma.GSTRuleScalarFieldEnum = {
  id: 'id',
  hsnCode: 'hsnCode',
  cgst: 'cgst',
  sgst: 'sgst',
  igst: 'igst',
  utgst: 'utgst'
};

exports.Prisma.ExchangeProgramScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isActive: 'isActive'
};

exports.Prisma.DeviceCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.ExchangeRuleScalarFieldEnum = {
  id: 'id',
  exchangeProgramId: 'exchangeProgramId',
  deviceCategoryId: 'deviceCategoryId',
  brand: 'brand',
  modelName: 'modelName',
  maxValuation: 'maxValuation',
  conditionsJson: 'conditionsJson'
};

exports.Prisma.WarehouseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  countryCode: 'countryCode',
  state: 'state',
  city: 'city',
  pincode: 'pincode',
  isActive: 'isActive'
};

exports.Prisma.ShippingSLAScalarFieldEnum = {
  id: 'id',
  sourceState: 'sourceState',
  destState: 'destState',
  transitDays: 'transitDays',
  cutoffHour: 'cutoffHour'
};

exports.Prisma.HolidayCalendarScalarFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  date: 'date',
  name: 'name'
};

exports.Prisma.FestivalCampaignScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate',
  themeJson: 'themeJson',
  isActive: 'isActive'
};

exports.Prisma.FestivalBannerScalarFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  imageUrl: 'imageUrl',
  targetUrl: 'targetUrl',
  position: 'position'
};

exports.Prisma.FestivalLayoutScalarFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  sectionName: 'sectionName',
  sortOrder: 'sortOrder',
  configJson: 'configJson'
};

exports.Prisma.FestivalCouponScalarFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  code: 'code',
  discountPercent: 'discountPercent'
};

exports.Prisma.FestivalCollectionScalarFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  collectionId: 'collectionId'
};

exports.Prisma.BankOfferScalarFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  bankName: 'bankName',
  cardType: 'cardType',
  minTxnAmount: 'minTxnAmount',
  discountType: 'discountType',
  discountValue: 'discountValue',
  maxDiscount: 'maxDiscount',
  isActive: 'isActive'
};

exports.Prisma.EMIPlanScalarFieldEnum = {
  id: 'id',
  bankOfferId: 'bankOfferId',
  months: 'months',
  interestRate: 'interestRate',
  isNoCost: 'isNoCost',
  minAmount: 'minAmount'
};

exports.Prisma.PaymentAvailabilityScalarFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  method: 'method',
  minAmount: 'minAmount',
  maxAmount: 'maxAmount',
  isActive: 'isActive'
};

exports.Prisma.RegionalConfigurationScalarFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  defaultLanguage: 'defaultLanguage',
  taxType: 'taxType',
  addressFieldsJson: 'addressFieldsJson'
};

exports.Prisma.ShippingZoneStateScalarFieldEnum = {
  id: 'id',
  shippingZoneId: 'shippingZoneId',
  stateId: 'stateId'
};

exports.Prisma.FeatureFlagScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description',
  enabled: 'enabled',
  rolloutPct: 'rolloutPct',
  rulesJson: 'rulesJson',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.MediaOrderByRelevanceFieldEnum = {
  id: 'id',
  assetKey: 'assetKey',
  derivedFromId: 'derivedFromId',
  filename: 'filename',
  originalName: 'originalName',
  mimeType: 'mimeType',
  extension: 'extension',
  fileHash: 'fileHash',
  storageProvider: 'storageProvider',
  path: 'path',
  publicUrl: 'publicUrl',
  alt: 'alt',
  caption: 'caption',
  dominantColor: 'dominantColor',
  blurHash: 'blurHash',
  uploadedById: 'uploadedById',
  aiCaption: 'aiCaption',
  aiTags: 'aiTags',
  ocrText: 'ocrText',
  labels: 'labels',
  scene: 'scene',
  objects: 'objects',
  faces: 'faces',
  brand: 'brand',
  keywords: 'keywords',
  colorPalette: 'colorPalette',
  embeddingVector: 'embeddingVector',
  similarityHash: 'similarityHash',
  folderId: 'folderId'
};

exports.Prisma.MediaFolderOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId'
};

exports.Prisma.MediaCollectionOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description'
};

exports.Prisma.MediaCollectionMappingOrderByRelevanceFieldEnum = {
  mediaId: 'mediaId',
  collectionId: 'collectionId'
};

exports.Prisma.MediaVersionOrderByRelevanceFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  fileName: 'fileName',
  storagePath: 'storagePath',
  publicUrl: 'publicUrl',
  fileHash: 'fileHash',
  mimeType: 'mimeType',
  createdById: 'createdById'
};

exports.Prisma.MediaVariantOrderByRelevanceFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  variantName: 'variantName',
  mimeType: 'mimeType',
  storagePath: 'storagePath',
  publicUrl: 'publicUrl'
};

exports.Prisma.MediaTagOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug'
};

exports.Prisma.MediaTagMappingOrderByRelevanceFieldEnum = {
  mediaId: 'mediaId',
  tagId: 'tagId'
};

exports.Prisma.MediaUsageOrderByRelevanceFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  entityType: 'entityType',
  entityId: 'entityId',
  field: 'field'
};

exports.Prisma.AssetMetadataOrderByRelevanceFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  key: 'key',
  value: 'value',
  type: 'type'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  avatarId: 'avatarId',
  language: 'language',
  currency: 'currency',
  theme: 'theme',
  savedPreferences: 'savedPreferences',
  notificationPrefs: 'notificationPrefs'
};

exports.Prisma.UserSessionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  deviceName: 'deviceName',
  browser: 'browser',
  browserVersion: 'browserVersion',
  os: 'os',
  ip: 'ip',
  country: 'country',
  city: 'city',
  userAgent: 'userAgent'
};

exports.Prisma.TokenOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  hash: 'hash'
};

exports.Prisma.AddressOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  phone: 'phone',
  company: 'company',
  label: 'label',
  street: 'street',
  landmark: 'landmark',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  country: 'country',
  deliveryInstructions: 'deliveryInstructions'
};

exports.Prisma.CategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  parentId: 'parentId',
  iconMediaId: 'iconMediaId',
  bannerMediaId: 'bannerMediaId',
  thumbnailMediaId: 'thumbnailMediaId'
};

exports.Prisma.BrandOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  mediaId: 'mediaId',
  description: 'description'
};

exports.Prisma.CollectionOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  rules: 'rules'
};

exports.Prisma.CollectionProductOrderByRelevanceFieldEnum = {
  collectionId: 'collectionId',
  productId: 'productId'
};

exports.Prisma.ProductOrderByRelevanceFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  categoryId: 'categoryId',
  name: 'name',
  slug: 'slug',
  shortDescription: 'shortDescription',
  longDescription: 'longDescription',
  hsnCode: 'hsnCode',
  taxClass: 'taxClass'
};

exports.Prisma.ProductSlugHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  oldSlug: 'oldSlug',
  newSlug: 'newSlug'
};

exports.Prisma.ProductSeoOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  keywords: 'keywords',
  ogImageId: 'ogImageId'
};

exports.Prisma.CategorySeoOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  ogImageId: 'ogImageId'
};

exports.Prisma.BrandSeoOrderByRelevanceFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  ogImageId: 'ogImageId'
};

exports.Prisma.TagOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug'
};

exports.Prisma.ProductTagOrderByRelevanceFieldEnum = {
  productId: 'productId',
  tagId: 'tagId'
};

exports.Prisma.ProductImageOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  mediaId: 'mediaId',
  type: 'type'
};

exports.Prisma.AttributeOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type'
};

exports.Prisma.AttributeValueOrderByRelevanceFieldEnum = {
  id: 'id',
  attributeId: 'attributeId',
  value: 'value',
  meta: 'meta'
};

exports.Prisma.ProductAttributeOrderByRelevanceFieldEnum = {
  productId: 'productId',
  attributeId: 'attributeId'
};

exports.Prisma.ProductVariantOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  sku: 'sku',
  barcode: 'barcode',
  name: 'name'
};

exports.Prisma.ProductPriceOrderByRelevanceFieldEnum = {
  id: 'id',
  productVariantId: 'productVariantId',
  currency: 'currency'
};

exports.Prisma.VariantAttributeOrderByRelevanceFieldEnum = {
  variantId: 'variantId',
  attributeValueId: 'attributeValueId'
};

exports.Prisma.SpecificationGroupOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.SpecificationOrderByRelevanceFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  name: 'name'
};

exports.Prisma.ProductSpecificationOrderByRelevanceFieldEnum = {
  productId: 'productId',
  specId: 'specId',
  value: 'value'
};

exports.Prisma.InventoryOrderByRelevanceFieldEnum = {
  id: 'id',
  variantId: 'variantId',
  status: 'status',
  warehouseId: 'warehouseId'
};

exports.Prisma.InventoryMovementOrderByRelevanceFieldEnum = {
  id: 'id',
  inventoryId: 'inventoryId',
  type: 'type',
  referenceId: 'referenceId',
  notes: 'notes'
};

exports.Prisma.CartOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId'
};

exports.Prisma.CartItemOrderByRelevanceFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  variantId: 'variantId'
};

exports.Prisma.WishlistOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId'
};

exports.Prisma.WishlistItemOrderByRelevanceFieldEnum = {
  id: 'id',
  wishlistId: 'wishlistId',
  productId: 'productId'
};

exports.Prisma.ShippingProviderOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.ShippingZoneOrderByRelevanceFieldEnum = {
  id: 'id',
  shippingProviderId: 'shippingProviderId',
  name: 'name',
  countries: 'countries'
};

exports.Prisma.ShippingRateOrderByRelevanceFieldEnum = {
  id: 'id',
  zoneId: 'zoneId',
  methodName: 'methodName',
  estDays: 'estDays'
};

exports.Prisma.CheckoutSessionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  cartId: 'cartId',
  shippingAddress: 'shippingAddress',
  billingAddress: 'billingAddress',
  couponCode: 'couponCode',
  shippingMethod: 'shippingMethod',
  paymentMethodCode: 'paymentMethodCode'
};

exports.Prisma.OrderOrderByRelevanceFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  userId: 'userId',
  checkoutSessionId: 'checkoutSessionId',
  shippingName: 'shippingName',
  shippingPhone: 'shippingPhone',
  shippingEmail: 'shippingEmail',
  shippingStreet: 'shippingStreet',
  shippingCity: 'shippingCity',
  shippingState: 'shippingState',
  shippingCountry: 'shippingCountry',
  shippingPostalCode: 'shippingPostalCode',
  billingAddr: 'billingAddr',
  gstin: 'gstin',
  companyName: 'companyName',
  invoiceType: 'invoiceType',
  couponCode: 'couponCode',
  discountType: 'discountType',
  shippingProvider: 'shippingProvider',
  trackingNumber: 'trackingNumber',
  estimatedDelivery: 'estimatedDelivery'
};

exports.Prisma.OrderTimelineOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  status: 'status',
  message: 'message',
  createdBy: 'createdBy'
};

exports.Prisma.OrderItemOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  variantId: 'variantId',
  productName: 'productName',
  brandName: 'brandName',
  sku: 'sku'
};

exports.Prisma.ReturnOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  reason: 'reason',
  status: 'status'
};

exports.Prisma.ReturnItemOrderByRelevanceFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  orderItemId: 'orderItemId'
};

exports.Prisma.RefundOrderByRelevanceFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  paymentId: 'paymentId',
  reason: 'reason',
  providerRefundId: 'providerRefundId'
};

exports.Prisma.CouponOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  discountType: 'discountType',
  categoryRestrictions: 'categoryRestrictions',
  productRestrictions: 'productRestrictions',
  excludedProducts: 'excludedProducts'
};

exports.Prisma.CouponRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  couponId: 'couponId',
  type: 'type'
};

exports.Prisma.CouponConditionOrderByRelevanceFieldEnum = {
  id: 'id',
  ruleId: 'ruleId',
  field: 'field',
  operator: 'operator',
  value: 'value'
};

exports.Prisma.CouponUsageOrderByRelevanceFieldEnum = {
  id: 'id',
  couponId: 'couponId',
  userId: 'userId',
  orderId: 'orderId'
};

exports.Prisma.PaymentOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  currency: 'currency',
  paymentMethodCode: 'paymentMethodCode',
  provider: 'provider',
  providerPaymentId: 'providerPaymentId',
  providerOrderId: 'providerOrderId',
  failureReason: 'failureReason'
};

exports.Prisma.PaymentMethodOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description'
};

exports.Prisma.PaymentProviderOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name'
};

exports.Prisma.PaymentMethodProviderOrderByRelevanceFieldEnum = {
  id: 'id',
  paymentMethodId: 'paymentMethodId',
  providerId: 'providerId',
  config: 'config'
};

exports.Prisma.PaymentProviderConfigOrderByRelevanceFieldEnum = {
  id: 'id',
  providerId: 'providerId',
  environment: 'environment',
  key: 'key',
  encryptedSecret: 'encryptedSecret',
  webhookSecret: 'webhookSecret'
};

exports.Prisma.PaymentMethodRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  paymentMethodId: 'paymentMethodId',
  allowedPincodes: 'allowedPincodes',
  blockedPincodes: 'blockedPincodes',
  allowedCategories: 'allowedCategories',
  blockedCategories: 'blockedCategories'
};

exports.Prisma.PaymentEventOrderByRelevanceFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  providerPaymentId: 'providerPaymentId',
  rawPayload: 'rawPayload',
  errorMessage: 'errorMessage'
};

exports.Prisma.PaymentAttemptOrderByRelevanceFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  providerPaymentId: 'providerPaymentId',
  errorMessage: 'errorMessage'
};

exports.Prisma.PaymentWebhookOrderByRelevanceFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  provider: 'provider',
  eventId: 'eventId',
  eventType: 'eventType',
  rawPayload: 'rawPayload',
  signature: 'signature'
};

exports.Prisma.PaymentAuditOrderByRelevanceFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  action: 'action',
  providerResponse: 'providerResponse'
};

exports.Prisma.TaxRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  country: 'country',
  state: 'state'
};

exports.Prisma.ReviewOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  userId: 'userId',
  title: 'title',
  comment: 'comment'
};

exports.Prisma.NotificationOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  type: 'type',
  recipientId: 'recipientId',
  recipientContact: 'recipientContact',
  templateId: 'templateId',
  payload: 'payload',
  title: 'title',
  body: 'body'
};

exports.Prisma.NotificationActionOrderByRelevanceFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  label: 'label',
  url: 'url',
  type: 'type'
};

exports.Prisma.NotificationJobOrderByRelevanceFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  lastError: 'lastError'
};

exports.Prisma.NotificationLogOrderByRelevanceFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  recipient: 'recipient',
  provider: 'provider',
  templateId: 'templateId',
  response: 'response'
};

exports.Prisma.NotificationTemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  name: 'name',
  event: 'event',
  subject: 'subject',
  html: 'html',
  text: 'text',
  variables: 'variables'
};

exports.Prisma.NotificationTemplateVersionOrderByRelevanceFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  subject: 'subject',
  html: 'html',
  text: 'text',
  variables: 'variables',
  createdById: 'createdById'
};

exports.Prisma.NotificationSettingOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId'
};

exports.Prisma.PushDeviceOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  deviceToken: 'deviceToken',
  platform: 'platform',
  browser: 'browser'
};

exports.Prisma.WebhookSubscriptionOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  targetUrl: 'targetUrl',
  secret: 'secret',
  events: 'events'
};

exports.Prisma.SearchHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  query: 'query',
  clickedProductId: 'clickedProductId'
};

exports.Prisma.PopularSearchOrderByRelevanceFieldEnum = {
  id: 'id',
  query: 'query'
};

exports.Prisma.RecentlyViewedOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId'
};

exports.Prisma.SettingOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value',
  description: 'description'
};

exports.Prisma.AuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  action: 'action',
  changes: 'changes',
  userId: 'userId'
};

exports.Prisma.OrganizationOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.WebsiteOrderByRelevanceFieldEnum = {
  id: 'id',
  domain: 'domain',
  name: 'name',
  organizationId: 'organizationId',
  activeVersionId: 'activeVersionId'
};

exports.Prisma.WebsiteSettingsOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  brandName: 'brandName',
  websiteName: 'websiteName',
  logoUrl: 'logoUrl',
  faviconUrl: 'faviconUrl',
  tagline: 'tagline',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  businessAddress: 'businessAddress',
  defaultCurrency: 'defaultCurrency',
  defaultLanguage: 'defaultLanguage',
  searchPlaceholder: 'searchPlaceholder',
  copyright: 'copyright',
  socialLinksJson: 'socialLinksJson',
  supportEmail: 'supportEmail',
  supportPhone: 'supportPhone',
  announcementsJson: 'announcementsJson',
  trendingSearchesJson: 'trendingSearchesJson',
  paymentBadgesJson: 'paymentBadgesJson',
  megaMenuFeaturedJson: 'megaMenuFeaturedJson'
};

exports.Prisma.WebsiteDraftOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  name: 'name',
  version: 'version',
  status: 'status'
};

exports.Prisma.WebsiteVersionOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  versionLabel: 'versionLabel',
  payload: 'payload',
  hash: 'hash'
};

exports.Prisma.WebsiteThemeOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  name: 'name'
};

exports.Prisma.ThemeTokenOrderByRelevanceFieldEnum = {
  id: 'id',
  themeId: 'themeId',
  key: 'key',
  value: 'value'
};

exports.Prisma.WebsiteLayoutOrderByRelevanceFieldEnum = {
  id: 'id',
  themeId: 'themeId',
  name: 'name'
};

exports.Prisma.WebsitePageOrderByRelevanceFieldEnum = {
  id: 'id',
  layoutId: 'layoutId',
  title: 'title',
  slug: 'slug'
};

exports.Prisma.PageRouteOrderByRelevanceFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  routePath: 'routePath'
};

exports.Prisma.SeoOrderByRelevanceFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  title: 'title',
  description: 'description',
  canonical: 'canonical',
  robots: 'robots',
  schemaJson: 'schemaJson',
  twitterCard: 'twitterCard',
  ogImageId: 'ogImageId',
  faviconId: 'faviconId'
};

exports.Prisma.ComponentRegistryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  schema: 'schema',
  version: 'version'
};

exports.Prisma.WebsiteSectionOrderByRelevanceFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  name: 'name'
};

exports.Prisma.WebsiteComponentOrderByRelevanceFieldEnum = {
  id: 'id',
  sectionId: 'sectionId',
  registryId: 'registryId'
};

exports.Prisma.WebsiteComponentPropertyOrderByRelevanceFieldEnum = {
  id: 'id',
  componentId: 'componentId',
  key: 'key',
  bindingType: 'bindingType',
  literalValue: 'literalValue',
  entityType: 'entityType',
  entityId: 'entityId',
  expression: 'expression',
  schemaType: 'schemaType'
};

exports.Prisma.WebsiteNavigationOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  handle: 'handle',
  name: 'name',
  type: 'type'
};

exports.Prisma.WebsiteMenuOrderByRelevanceFieldEnum = {
  id: 'id',
  navigationId: 'navigationId',
  label: 'label',
  url: 'url',
  parentId: 'parentId'
};

exports.Prisma.WebsiteAIConfigOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  assistantName: 'assistantName',
  avatarUrl: 'avatarUrl',
  greeting: 'greeting',
  suggestionsJson: 'suggestionsJson',
  prompt: 'prompt',
  model: 'model',
  tone: 'tone'
};

exports.Prisma.ScriptInjectionOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  name: 'name',
  placement: 'placement',
  code: 'code'
};

exports.Prisma.MediaReferenceOrderByRelevanceFieldEnum = {
  id: 'id',
  websiteId: 'websiteId',
  mediaId: 'mediaId'
};

exports.Prisma.WebsiteBannerOrderByRelevanceFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  name: 'name',
  linkUrl: 'linkUrl',
  position: 'position'
};

exports.Prisma.AnalyticsEventOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  userId: 'userId',
  sessionId: 'sessionId',
  category: 'category',
  entityType: 'entityType',
  entityId: 'entityId',
  properties: 'properties',
  ipAddress: 'ipAddress',
  country: 'country',
  city: 'city',
  device: 'device',
  browser: 'browser',
  platform: 'platform',
  referrer: 'referrer',
  utmSource: 'utmSource',
  utmMedium: 'utmMedium',
  utmCampaign: 'utmCampaign'
};

exports.Prisma.AnalyticsSessionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  visitorId: 'visitorId',
  device: 'device',
  browser: 'browser',
  os: 'os',
  country: 'country',
  city: 'city',
  entryPage: 'entryPage',
  exitPage: 'exitPage'
};

exports.Prisma.AnalyticsPageViewOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  page: 'page',
  title: 'title',
  referrer: 'referrer'
};

exports.Prisma.AnalyticsHeatmapOrderByRelevanceFieldEnum = {
  id: 'id',
  page: 'page'
};

exports.Prisma.CustomerAnalyticsOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  favoriteCategory: 'favoriteCategory',
  favoriteBrand: 'favoriteBrand',
  customerSegment: 'customerSegment'
};

exports.Prisma.CampaignMetricsOrderByRelevanceFieldEnum = {
  id: 'id',
  campaign: 'campaign'
};

exports.Prisma.FeatureUsageMetricsOrderByRelevanceFieldEnum = {
  id: 'id',
  feature: 'feature'
};

exports.Prisma.AnalyticsProductMetricsOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId'
};

exports.Prisma.AnalyticsCategoryMetricsOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId'
};

exports.Prisma.AnalyticsSalesMetricsOrderByRelevanceFieldEnum = {
  id: 'id'
};

exports.Prisma.AnalyticsTrafficMetricsOrderByRelevanceFieldEnum = {
  id: 'id'
};

exports.Prisma.AnalyticsSearchMetricsOrderByRelevanceFieldEnum = {
  id: 'id',
  query: 'query'
};

exports.Prisma.AnalyticsFunnelOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.AnalyticsFunnelStepOrderByRelevanceFieldEnum = {
  id: 'id',
  funnelId: 'funnelId',
  name: 'name',
  event: 'event'
};

exports.Prisma.DashboardOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.DashboardWidgetOrderByRelevanceFieldEnum = {
  id: 'id',
  dashboardId: 'dashboardId',
  title: 'title',
  type: 'type',
  metric: 'metric'
};

exports.Prisma.DashboardLayoutOrderByRelevanceFieldEnum = {
  id: 'id',
  widgetId: 'widgetId',
  userId: 'userId'
};

exports.Prisma.ForecastDatasetOrderByRelevanceFieldEnum = {
  id: 'id',
  metric: 'metric',
  granularity: 'granularity'
};

exports.Prisma.AlertRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  metric: 'metric',
  operator: 'operator',
  severity: 'severity'
};

exports.Prisma.ScheduledReportOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  frequency: 'frequency',
  recipients: 'recipients',
  format: 'format',
  timezone: 'timezone'
};

exports.Prisma.AnalyticsDashboardCacheOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
};

exports.Prisma.AIProviderOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name'
};

exports.Prisma.AIModelOrderByRelevanceFieldEnum = {
  id: 'id',
  providerId: 'providerId',
  code: 'code',
  name: 'name'
};

exports.Prisma.AIConfigurationOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  defaultProvider: 'defaultProvider',
  defaultModel: 'defaultModel',
  enabledFeatures: 'enabledFeatures'
};

exports.Prisma.AIConversationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title'
};

exports.Prisma.AIMessageOrderByRelevanceFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content'
};

exports.Prisma.AIJobOrderByRelevanceFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  payload: 'payload',
  result: 'result',
  error: 'error'
};

exports.Prisma.AIUsageOrderByRelevanceFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  websiteId: 'websiteId',
  feature: 'feature',
  provider: 'provider',
  model: 'model'
};

exports.Prisma.AIPromptTemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  systemInstruction: 'systemInstruction',
  userPromptSchema: 'userPromptSchema',
  variables: 'variables'
};

exports.Prisma.AIEmbeddingOrderByRelevanceFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  vector: 'vector'
};

exports.Prisma.CountryOrderByRelevanceFieldEnum = {
  code: 'code',
  name: 'name',
  currency: 'currency',
  currencySymbol: 'currencySymbol',
  locale: 'locale',
  phonePrefix: 'phonePrefix'
};

exports.Prisma.StateOrderByRelevanceFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  code: 'code',
  name: 'name'
};

exports.Prisma.DistrictOrderByRelevanceFieldEnum = {
  id: 'id',
  stateId: 'stateId',
  name: 'name'
};

exports.Prisma.CityOrderByRelevanceFieldEnum = {
  id: 'id',
  districtId: 'districtId',
  name: 'name'
};

exports.Prisma.PincodeOrderByRelevanceFieldEnum = {
  code: 'code',
  cityId: 'cityId',
  stateId: 'stateId'
};

exports.Prisma.GSTRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  hsnCode: 'hsnCode'
};

exports.Prisma.ExchangeProgramOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.DeviceCategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.ExchangeRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  exchangeProgramId: 'exchangeProgramId',
  deviceCategoryId: 'deviceCategoryId',
  brand: 'brand',
  modelName: 'modelName',
  conditionsJson: 'conditionsJson'
};

exports.Prisma.WarehouseOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  countryCode: 'countryCode',
  state: 'state',
  city: 'city',
  pincode: 'pincode'
};

exports.Prisma.ShippingSLAOrderByRelevanceFieldEnum = {
  id: 'id',
  sourceState: 'sourceState',
  destState: 'destState'
};

exports.Prisma.HolidayCalendarOrderByRelevanceFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  name: 'name'
};

exports.Prisma.FestivalCampaignOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  themeJson: 'themeJson'
};

exports.Prisma.FestivalBannerOrderByRelevanceFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  imageUrl: 'imageUrl',
  targetUrl: 'targetUrl',
  position: 'position'
};

exports.Prisma.FestivalLayoutOrderByRelevanceFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  sectionName: 'sectionName',
  configJson: 'configJson'
};

exports.Prisma.FestivalCouponOrderByRelevanceFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  code: 'code'
};

exports.Prisma.FestivalCollectionOrderByRelevanceFieldEnum = {
  id: 'id',
  festivalCampaignId: 'festivalCampaignId',
  collectionId: 'collectionId'
};

exports.Prisma.BankOfferOrderByRelevanceFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  bankName: 'bankName',
  cardType: 'cardType',
  discountType: 'discountType'
};

exports.Prisma.EMIPlanOrderByRelevanceFieldEnum = {
  id: 'id',
  bankOfferId: 'bankOfferId'
};

exports.Prisma.PaymentAvailabilityOrderByRelevanceFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  method: 'method'
};

exports.Prisma.RegionalConfigurationOrderByRelevanceFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  defaultLanguage: 'defaultLanguage',
  taxType: 'taxType',
  addressFieldsJson: 'addressFieldsJson'
};

exports.Prisma.ShippingZoneStateOrderByRelevanceFieldEnum = {
  id: 'id',
  shippingZoneId: 'shippingZoneId',
  stateId: 'stateId'
};

exports.Prisma.FeatureFlagOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description',
  rulesJson: 'rulesJson'
};
exports.AssetType = exports.$Enums.AssetType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  AUDIO: 'AUDIO',
  PDF: 'PDF',
  DOCUMENT: 'DOCUMENT',
  MODEL_3D: 'MODEL_3D',
  FONT: 'FONT',
  SVG: 'SVG',
  LOTTIE: 'LOTTIE',
  ICON: 'ICON',
  AI_ASSET: 'AI_ASSET',
  OTHER: 'OTHER'
};

exports.MediaVisibility = exports.$Enums.MediaVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  MERCHANT_ONLY: 'MERCHANT_ONLY',
  SYSTEM: 'SYSTEM'
};

exports.MediaStatus = exports.$Enums.MediaStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  PROCESSING: 'PROCESSING'
};

exports.Gender = exports.$Enums.Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY'
};

exports.Role = exports.$Enums.Role = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  BLOCKED: 'BLOCKED',
  DELETED: 'DELETED'
};

exports.TokenType = exports.$Enums.TokenType = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  LOGIN_OTP: 'LOGIN_OTP'
};

exports.AddressType = exports.$Enums.AddressType = {
  HOME: 'HOME',
  OFFICE: 'OFFICE',
  OTHER: 'OTHER'
};

exports.ProductStatus = exports.$Enums.ProductStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  DISCONTINUED: 'DISCONTINUED'
};

exports.ProductVisibility = exports.$Enums.ProductVisibility = {
  PUBLIC: 'PUBLIC',
  HIDDEN: 'HIDDEN',
  SCHEDULED: 'SCHEDULED'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
  REFUNDED: 'REFUNDED'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
};

exports.PaymentMethodType = exports.$Enums.PaymentMethodType = {
  UPI: 'UPI',
  CARD: 'CARD',
  NETBANKING: 'NETBANKING',
  WALLET: 'WALLET',
  COD: 'COD',
  GIFT_CARD: 'GIFT_CARD'
};

exports.PaymentEventStatus = exports.$Enums.PaymentEventStatus = {
  CREATED: 'CREATED',
  AUTHORIZED: 'AUTHORIZED',
  FAILED: 'FAILED',
  SUCCESS: 'SUCCESS',
  REFUND_STARTED: 'REFUND_STARTED',
  REFUNDED: 'REFUNDED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED'
};

exports.NotificationCategory = exports.$Enums.NotificationCategory = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  SHIPPING: 'SHIPPING',
  AUTH: 'AUTH',
  PROMOTION: 'PROMOTION',
  SYSTEM: 'SYSTEM',
  SECURITY: 'SECURITY',
  MARKETING: 'MARKETING',
  AI: 'AI',
  MEDIA: 'MEDIA',
  ANALYTICS: 'ANALYTICS'
};

exports.NotificationChannel = exports.$Enums.NotificationChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  PUSH: 'PUSH',
  BROWSER: 'BROWSER',
  WEBHOOK: 'WEBHOOK',
  SLACK: 'SLACK',
  DISCORD: 'DISCORD'
};

exports.NotificationPriority = exports.$Enums.NotificationPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.NotificationStatus = exports.$Enums.NotificationStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
  CANCELLED: 'CANCELLED',
  DEAD: 'DEAD'
};

exports.AnalyticsEventType = exports.$Enums.AnalyticsEventType = {
  PAGE_VIEW: 'PAGE_VIEW',
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  SEARCH: 'SEARCH',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CHECKOUT: 'CHECKOUT',
  PAYMENT: 'PAYMENT',
  PURCHASE: 'PURCHASE',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',
  REFUND: 'REFUND',
  RETURN: 'RETURN',
  NOTIFICATION_OPEN: 'NOTIFICATION_OPEN',
  MEDIA_VIEW: 'MEDIA_VIEW'
};

exports.Prisma.ModelName = {
  Media: 'Media',
  MediaFolder: 'MediaFolder',
  MediaCollection: 'MediaCollection',
  MediaCollectionMapping: 'MediaCollectionMapping',
  MediaVersion: 'MediaVersion',
  MediaVariant: 'MediaVariant',
  MediaTag: 'MediaTag',
  MediaTagMapping: 'MediaTagMapping',
  MediaUsage: 'MediaUsage',
  AssetMetadata: 'AssetMetadata',
  User: 'User',
  UserSession: 'UserSession',
  Token: 'Token',
  Address: 'Address',
  Category: 'Category',
  Brand: 'Brand',
  Collection: 'Collection',
  CollectionProduct: 'CollectionProduct',
  Product: 'Product',
  ProductSlugHistory: 'ProductSlugHistory',
  ProductSeo: 'ProductSeo',
  CategorySeo: 'CategorySeo',
  BrandSeo: 'BrandSeo',
  Tag: 'Tag',
  ProductTag: 'ProductTag',
  ProductImage: 'ProductImage',
  Attribute: 'Attribute',
  AttributeValue: 'AttributeValue',
  ProductAttribute: 'ProductAttribute',
  ProductVariant: 'ProductVariant',
  ProductPrice: 'ProductPrice',
  VariantAttribute: 'VariantAttribute',
  SpecificationGroup: 'SpecificationGroup',
  Specification: 'Specification',
  ProductSpecification: 'ProductSpecification',
  Inventory: 'Inventory',
  InventoryMovement: 'InventoryMovement',
  Cart: 'Cart',
  CartItem: 'CartItem',
  Wishlist: 'Wishlist',
  WishlistItem: 'WishlistItem',
  ShippingProvider: 'ShippingProvider',
  ShippingZone: 'ShippingZone',
  ShippingRate: 'ShippingRate',
  CheckoutSession: 'CheckoutSession',
  Order: 'Order',
  OrderTimeline: 'OrderTimeline',
  OrderItem: 'OrderItem',
  Return: 'Return',
  ReturnItem: 'ReturnItem',
  Refund: 'Refund',
  Coupon: 'Coupon',
  CouponRule: 'CouponRule',
  CouponCondition: 'CouponCondition',
  CouponUsage: 'CouponUsage',
  Payment: 'Payment',
  PaymentMethod: 'PaymentMethod',
  PaymentProvider: 'PaymentProvider',
  PaymentMethodProvider: 'PaymentMethodProvider',
  PaymentProviderConfig: 'PaymentProviderConfig',
  PaymentMethodRule: 'PaymentMethodRule',
  PaymentEvent: 'PaymentEvent',
  PaymentAttempt: 'PaymentAttempt',
  PaymentWebhook: 'PaymentWebhook',
  PaymentAudit: 'PaymentAudit',
  TaxRule: 'TaxRule',
  Review: 'Review',
  Notification: 'Notification',
  NotificationAction: 'NotificationAction',
  NotificationJob: 'NotificationJob',
  NotificationLog: 'NotificationLog',
  NotificationTemplate: 'NotificationTemplate',
  NotificationTemplateVersion: 'NotificationTemplateVersion',
  NotificationSetting: 'NotificationSetting',
  PushDevice: 'PushDevice',
  WebhookSubscription: 'WebhookSubscription',
  SearchHistory: 'SearchHistory',
  PopularSearch: 'PopularSearch',
  RecentlyViewed: 'RecentlyViewed',
  Setting: 'Setting',
  AuditLog: 'AuditLog',
  Organization: 'Organization',
  Website: 'Website',
  WebsiteSettings: 'WebsiteSettings',
  WebsiteDraft: 'WebsiteDraft',
  WebsiteVersion: 'WebsiteVersion',
  WebsiteTheme: 'WebsiteTheme',
  ThemeToken: 'ThemeToken',
  WebsiteLayout: 'WebsiteLayout',
  WebsitePage: 'WebsitePage',
  PageRoute: 'PageRoute',
  Seo: 'Seo',
  ComponentRegistry: 'ComponentRegistry',
  WebsiteSection: 'WebsiteSection',
  WebsiteComponent: 'WebsiteComponent',
  WebsiteComponentProperty: 'WebsiteComponentProperty',
  WebsiteNavigation: 'WebsiteNavigation',
  WebsiteMenu: 'WebsiteMenu',
  WebsiteAIConfig: 'WebsiteAIConfig',
  ScriptInjection: 'ScriptInjection',
  MediaReference: 'MediaReference',
  WebsiteBanner: 'WebsiteBanner',
  AnalyticsEvent: 'AnalyticsEvent',
  AnalyticsSession: 'AnalyticsSession',
  AnalyticsPageView: 'AnalyticsPageView',
  AnalyticsHeatmap: 'AnalyticsHeatmap',
  CustomerAnalytics: 'CustomerAnalytics',
  CampaignMetrics: 'CampaignMetrics',
  FeatureUsageMetrics: 'FeatureUsageMetrics',
  AnalyticsProductMetrics: 'AnalyticsProductMetrics',
  AnalyticsCategoryMetrics: 'AnalyticsCategoryMetrics',
  AnalyticsSalesMetrics: 'AnalyticsSalesMetrics',
  AnalyticsTrafficMetrics: 'AnalyticsTrafficMetrics',
  AnalyticsSearchMetrics: 'AnalyticsSearchMetrics',
  AnalyticsFunnel: 'AnalyticsFunnel',
  AnalyticsFunnelStep: 'AnalyticsFunnelStep',
  Dashboard: 'Dashboard',
  DashboardWidget: 'DashboardWidget',
  DashboardLayout: 'DashboardLayout',
  ForecastDataset: 'ForecastDataset',
  AlertRule: 'AlertRule',
  ScheduledReport: 'ScheduledReport',
  AnalyticsDashboardCache: 'AnalyticsDashboardCache',
  AIProvider: 'AIProvider',
  AIModel: 'AIModel',
  AIConfiguration: 'AIConfiguration',
  AIConversation: 'AIConversation',
  AIMessage: 'AIMessage',
  AIJob: 'AIJob',
  AIUsage: 'AIUsage',
  AIPromptTemplate: 'AIPromptTemplate',
  AIEmbedding: 'AIEmbedding',
  Country: 'Country',
  State: 'State',
  District: 'District',
  City: 'City',
  Pincode: 'Pincode',
  GSTRule: 'GSTRule',
  ExchangeProgram: 'ExchangeProgram',
  DeviceCategory: 'DeviceCategory',
  ExchangeRule: 'ExchangeRule',
  Warehouse: 'Warehouse',
  ShippingSLA: 'ShippingSLA',
  HolidayCalendar: 'HolidayCalendar',
  FestivalCampaign: 'FestivalCampaign',
  FestivalBanner: 'FestivalBanner',
  FestivalLayout: 'FestivalLayout',
  FestivalCoupon: 'FestivalCoupon',
  FestivalCollection: 'FestivalCollection',
  BankOffer: 'BankOffer',
  EMIPlan: 'EMIPlan',
  PaymentAvailability: 'PaymentAvailability',
  RegionalConfiguration: 'RegionalConfiguration',
  ShippingZoneState: 'ShippingZoneState',
  FeatureFlag: 'FeatureFlag'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
