import type {
  Brand,
  Category,
  Collection,
  Coupon,
  HeroSlide,
  MegaMenuSection,
  NavLink,
  Product,
  Testimonial,
} from './types'

export const navLinks: NavLink[] = [
  { label: 'New', href: '/category/new-arrivals', badge: 'Fresh' },
  { label: 'Women', href: '/category/fashion' },
  { label: 'Men', href: '/category/fashion' },
  { label: 'Tech', href: '/category/tech' },
  { label: 'Home', href: '/category/home' },
  { label: 'Beauty', href: '/category/beauty' },
  { label: 'Sale', href: '/category/sale', badge: 'Up to 60%' },
]

export const megaMenu: MegaMenuSection[] = [
  {
    label: 'Shop',
    href: '/category/all',
    columns: [
      {
        title: 'Categories',
        links: [
          { label: 'Fashion', href: '/category/fashion' },
          { label: 'Technology', href: '/category/tech' },
          { label: 'Home & Living', href: '/category/home' },
          { label: 'Beauty', href: '/category/beauty' },
          { label: 'Footwear', href: '/category/footwear' },
          { label: 'Accessories', href: '/category/accessories' },
        ],
      },
      {
        title: 'Collections',
        links: [
          { label: 'The Essentials', href: '/category/all' },
          { label: 'New Arrivals', href: '/category/new-arrivals' },
          { label: 'Best Sellers', href: '/category/all' },
          { label: 'Luxury Edit', href: '/category/all' },
          { label: 'Gifts', href: '/category/all' },
        ],
      },
      {
        title: 'Support',
        links: [
          { label: 'Track Order', href: '/account/orders' },
          { label: 'Returns', href: '/account/returns' },
          { label: 'Shipping', href: '/category/all' },
          { label: 'Contact Us', href: '/category/all' },
        ],
      },
    ],
    featured: {
      title: 'Autumn Luxury Edit',
      subtitle: 'Discover the season’s most coveted pieces',
      image: '/images/cat-fashion.png',
      href: '/category/fashion',
    },
  },
]

export const categories: Category[] = [
  {
    id: 'c1',
    name: 'Fashion',
    slug: 'fashion',
    image: '/images/cat-fashion.png',
    productCount: 1284,
    description: 'Elevated wardrobe staples and statement pieces.',
  },
  {
    id: 'c2',
    name: 'Technology',
    slug: 'tech',
    image: '/images/cat-tech.png',
    productCount: 642,
    description: 'Considered tech for a connected life.',
  },
  {
    id: 'c3',
    name: 'Home & Living',
    slug: 'home',
    image: '/images/cat-home.png',
    productCount: 918,
    description: 'Objects that make a house feel like home.',
  },
  {
    id: 'c4',
    name: 'Beauty',
    slug: 'beauty',
    image: '/images/cat-beauty.png',
    productCount: 473,
    description: 'Skincare and rituals for everyday glow.',
  },
  {
    id: 'c5',
    name: 'Footwear',
    slug: 'footwear',
    image: '/images/cat-footwear.png',
    productCount: 356,
    description: 'From daily comfort to occasion-ready.',
  },
  {
    id: 'c6',
    name: 'Accessories',
    slug: 'accessories',
    image: '/images/cat-accessories.png',
    productCount: 521,
    description: 'The finishing touches that matter.',
  },
]

export const brands: Brand[] = [
  { id: 'b1', name: 'Auralis', logoText: 'AURALIS', href: '/category/all' },
  { id: 'b2', name: 'Northwood', logoText: 'NORTHWOOD', href: '/category/all' },
  { id: 'b3', name: 'Maison Vela', logoText: 'MAISON VELA', href: '/category/all' },
  { id: 'b4', name: 'Lumen', logoText: 'LUMEN', href: '/category/all' },
  { id: 'b5', name: 'Terra&Co', logoText: 'TERRA & CO', href: '/category/all' },
  { id: 'b6', name: 'Onyx', logoText: 'ONYX', href: '/category/all' },
]

const sampleReviews = (name: string) => [
  {
    id: 'r1',
    author: 'Amelia R.',
    rating: 5,
    date: '2 weeks ago',
    title: 'Exceeded expectations',
    body: `The ${name} feels even more premium in person. Beautiful finish and worth every penny.`,
    verified: true,
    helpful: 34,
  },
  {
    id: 'r2',
    author: 'Daniel K.',
    rating: 4,
    date: '1 month ago',
    title: 'Really impressive',
    body: 'Fast delivery and the quality is fantastic. Took one star off for the packaging only.',
    verified: true,
    helpful: 12,
  },
  {
    id: 'r3',
    author: 'Priya S.',
    rating: 5,
    date: '1 month ago',
    title: 'My new favourite',
    body: 'I keep getting compliments. The attention to detail is exactly what I hoped for.',
    verified: true,
    helpful: 21,
  },
]

const colorVariant = (colors: { id: string; label: string; value: string }[]) => ({
  type: 'color' as const,
  label: 'Color',
  options: colors.map((c) => ({ ...c, available: true })),
})

const sizeVariant = (sizes: string[], unavailable: string[] = []) => ({
  type: 'size' as const,
  label: 'Size',
  options: sizes.map((s) => ({
    id: s.toLowerCase(),
    label: s,
    available: !unavailable.includes(s),
  })),
})

export const products: Product[] = [
  {
    id: 'p1',
    slug: 'aeon-wireless-headphones',
    name: 'Aeon Wireless Headphones',
    brand: 'Auralis',
    category: 'tech',
    price: 349,
    oldPrice: 429,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 1247,
    images: ['/images/p-headphones.png', '/images/p-earbuds.png'],
    colors: ['#1c1c1c', '#c8a98a', '#e6e1d8'],
    badge: '19% OFF',
    inStock: true,
    stockCount: 8,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'Studio-grade adaptive noise cancellation, 40-hour battery, and plush memory-foam cushions engineered for all-day comfort.',
    highlights: [
      'Adaptive noise cancellation',
      '40-hour battery life',
      'Spatial audio with head tracking',
      'USB-C fast charge',
    ],
    specifications: [
      { label: 'Driver', value: '40mm dynamic' },
      { label: 'Battery', value: '40 hours' },
      { label: 'Bluetooth', value: '5.3 multipoint' },
      { label: 'Weight', value: '248g' },
    ],
    variants: [
      colorVariant([
        { id: 'black', label: 'Midnight', value: '#1c1c1c' },
        { id: 'sand', label: 'Sand', value: '#c8a98a' },
        { id: 'ivory', label: 'Ivory', value: '#e6e1d8' },
      ]),
    ],
  },
  {
    id: 'p2',
    slug: 'cloud-runner-sneaker',
    name: 'Cloud Runner Sneaker',
    brand: 'Northwood',
    category: 'footwear',
    price: 168,
    oldPrice: 210,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 892,
    images: ['/images/p-sneaker.png', '/images/cat-footwear.png'],
    colors: ['#f2efe9', '#1c1c1c'],
    badge: 'Best Seller',
    inStock: true,
    stockCount: 24,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'A featherlight everyday sneaker with a cushioned cloud sole and premium full-grain leather upper.',
    highlights: ['Full-grain leather', 'Responsive cloud sole', 'Machine washable', 'Vegan lining'],
    specifications: [
      { label: 'Upper', value: 'Full-grain leather' },
      { label: 'Sole', value: 'CloudFoam' },
      { label: 'Drop', value: '8mm' },
    ],
    variants: [
      colorVariant([
        { id: 'ivory', label: 'Ivory', value: '#f2efe9' },
        { id: 'black', label: 'Black', value: '#1c1c1c' },
      ]),
      sizeVariant(['6', '7', '8', '9', '10', '11', '12'], ['12']),
    ],
  },
  {
    id: 'p3',
    slug: 'meridian-automatic-watch',
    name: 'Meridian Automatic Watch',
    brand: 'Maison Vela',
    category: 'accessories',
    price: 540,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 421,
    images: ['/images/p-watch.png'],
    colors: ['#c8a98a', '#1c1c1c'],
    badge: 'New',
    inStock: true,
    stockCount: 5,
    freeDelivery: true,
    isNew: true,
    description:
      'A refined automatic timepiece with a sapphire crystal, exhibition caseback, and vegetable-tanned leather strap.',
    highlights: ['Sapphire crystal', 'Automatic movement', '50m water resistance', 'Italian leather strap'],
    specifications: [
      { label: 'Movement', value: 'Automatic' },
      { label: 'Case', value: '39mm steel' },
      { label: 'Crystal', value: 'Sapphire' },
      { label: 'Strap', value: 'Leather' },
    ],
  },
  {
    id: 'p4',
    slug: 'atelier-leather-tote',
    name: 'Atelier Leather Tote',
    brand: 'Maison Vela',
    category: 'accessories',
    price: 420,
    oldPrice: 520,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 318,
    images: ['/images/p-bag.png'],
    colors: ['#c8a98a', '#1c1c1c'],
    badge: '19% OFF',
    inStock: true,
    stockCount: 11,
    freeDelivery: true,
    description:
      'A structured tote handcrafted from vegetable-tanned leather with a suede-lined interior and laptop sleeve.',
    highlights: ['Vegetable-tanned leather', 'Suede lining', 'Fits 15" laptop', 'Lifetime repair'],
  },
  {
    id: 'p5',
    slug: 'eclipse-sunglasses',
    name: 'Eclipse Acetate Sunglasses',
    brand: 'Lumen',
    category: 'accessories',
    price: 145,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 206,
    images: ['/images/p-sunglasses.png'],
    inStock: true,
    stockCount: 30,
    freeDelivery: true,
    isNew: true,
    description: 'Hand-polished acetate frames with polarized, UV400 lenses in a timeless silhouette.',
    highlights: ['Polarized UV400', 'Italian acetate', 'Anti-scratch coating'],
  },
  {
    id: 'p6',
    slug: 'orbit-smart-speaker',
    name: 'Orbit Smart Speaker',
    brand: 'Auralis',
    category: 'tech',
    price: 129,
    oldPrice: 159,
    currency: 'USD',
    rating: 4.4,
    reviewCount: 534,
    images: ['/images/p-speaker.png'],
    colors: ['#e6e1d8', '#1c1c1c'],
    badge: '19% OFF',
    inStock: true,
    stockCount: 18,
    freeDelivery: true,
    description: 'Room-filling 360° sound with voice assistant and multi-room sync in a compact fabric-wrapped body.',
    highlights: ['360° sound', 'Voice assistant', 'Multi-room sync'],
  },
  {
    id: 'p7',
    slug: 'heritage-trench-coat',
    name: 'Heritage Trench Coat',
    brand: 'Northwood',
    category: 'fashion',
    price: 298,
    oldPrice: 380,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 267,
    images: ['/images/p-coat.png'],
    colors: ['#c8a98a', '#3a3733'],
    badge: 'Best Seller',
    inStock: true,
    stockCount: 9,
    freeDelivery: true,
    isBestSeller: true,
    description: 'A timeless double-breasted trench in water-resistant cotton gabardine with a removable liner.',
    highlights: ['Water-resistant', 'Removable liner', 'Cotton gabardine'],
    variants: [sizeVariant(['XS', 'S', 'M', 'L', 'XL'], ['XS'])],
  },
  {
    id: 'p8',
    slug: 'ember-ceramic-candle',
    name: 'Ember Ceramic Candle',
    brand: 'Terra&Co',
    category: 'home',
    price: 48,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 612,
    images: ['/images/p-candle.png'],
    inStock: true,
    stockCount: 40,
    freeDelivery: false,
    description: 'A slow-burning soy candle in a hand-glazed ceramic vessel — notes of amber, cedar, and vanilla.',
    highlights: ['60-hour burn', 'Soy wax', 'Refillable vessel'],
  },
  {
    id: 'p9',
    slug: 'lumen-radiance-serum',
    name: 'Lumen Radiance Serum',
    brand: 'Lumen',
    category: 'beauty',
    price: 62,
    oldPrice: 78,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 1043,
    images: ['/images/p-serum.png'],
    badge: '20% OFF',
    inStock: true,
    stockCount: 27,
    freeDelivery: true,
    isBestSeller: true,
    description: 'A brightening vitamin-C serum with hyaluronic acid for a visibly luminous, even complexion.',
    highlights: ['15% Vitamin C', 'Hyaluronic acid', 'Cruelty-free', 'Fragrance-free'],
  },
  {
    id: 'p10',
    slug: 'pulse-wireless-earbuds',
    name: 'Pulse Wireless Earbuds',
    brand: 'Auralis',
    category: 'tech',
    price: 179,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 758,
    images: ['/images/p-earbuds.png', '/images/p-headphones.png'],
    colors: ['#e6e1d8', '#1c1c1c'],
    badge: 'New',
    inStock: true,
    stockCount: 15,
    freeDelivery: true,
    isNew: true,
    description: 'Compact earbuds with active noise cancellation, wireless charging, and 30-hour total battery.',
    highlights: ['Active noise cancellation', 'Wireless charging', '30-hour battery'],
  },
  {
    id: 'p11',
    slug: 'nordic-lounge-chair',
    name: 'Nordic Lounge Chair',
    brand: 'Terra&Co',
    category: 'home',
    price: 890,
    oldPrice: 1100,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 143,
    images: ['/images/p-chair.png'],
    colors: ['#c8a98a', '#3a3733'],
    badge: 'Luxury',
    inStock: true,
    stockCount: 4,
    freeDelivery: true,
    description: 'A sculptural lounge chair with a solid oak frame and full-aniline leather seat that ages beautifully.',
    highlights: ['Solid oak frame', 'Full-aniline leather', 'Handmade'],
  },
  {
    id: 'p12',
    slug: 'carter-leather-wallet',
    name: 'Carter Leather Wallet',
    brand: 'Onyx',
    category: 'accessories',
    price: 89,
    oldPrice: 110,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 489,
    images: ['/images/p-wallet.png'],
    colors: ['#c8a98a', '#1c1c1c'],
    badge: 'Best Seller',
    inStock: false,
    stockCount: 0,
    freeDelivery: true,
    isBestSeller: true,
    description: 'A slim RFID-blocking bifold wallet in hand-burnished leather with six card slots.',
    highlights: ['RFID blocking', 'Hand-burnished leather', '6 card slots'],
  },
  {
    id: 'p13',
    slug: 'lambswool-crewneck-sweater',
    name: 'Lambswool Crewneck Sweater',
    brand: 'Northwood',
    category: 'fashion',
    price: 138,
    oldPrice: 175,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 384,
    images: ['/images/p-sweater.png'],
    colors: ['#d8cdba', '#3a3733', '#1c1c1c'],
    badge: '21% OFF',
    inStock: true,
    stockCount: 22,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'A cozy yet refined crewneck knit in pure lambswool with ribbed trims and a relaxed, everyday fit.',
    highlights: ['100% lambswool', 'Ribbed trims', 'Relaxed fit', 'Naturally warm'],
    specifications: [
      { label: 'Material', value: '100% lambswool' },
      { label: 'Fit', value: 'Relaxed' },
      { label: 'Care', value: 'Hand wash' },
    ],
    variants: [
      colorVariant([
        { id: 'oat', label: 'Oatmeal', value: '#d8cdba' },
        { id: 'charcoal', label: 'Charcoal', value: '#3a3733' },
        { id: 'black', label: 'Black', value: '#1c1c1c' },
      ]),
      sizeVariant(['XS', 'S', 'M', 'L', 'XL'], ['XS']),
    ],
  },
  {
    id: 'p14',
    slug: 'selvedge-denim-jeans',
    name: 'Selvedge Denim Jeans',
    brand: 'Northwood',
    category: 'fashion',
    price: 168,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 512,
    images: ['/images/p-jeans.png'],
    colors: ['#2f3d55', '#1c1c1c'],
    badge: 'New',
    inStock: true,
    stockCount: 31,
    freeDelivery: true,
    isNew: true,
    description:
      'Raw selvedge denim woven on vintage shuttle looms, cut in a timeless straight-leg silhouette.',
    highlights: ['Raw selvedge denim', 'Straight-leg fit', 'Copper hardware', 'Ages beautifully'],
    specifications: [
      { label: 'Fabric', value: '14oz selvedge' },
      { label: 'Fit', value: 'Straight leg' },
      { label: 'Rise', value: 'Mid rise' },
    ],
    variants: [
      colorVariant([
        { id: 'indigo', label: 'Raw Indigo', value: '#2f3d55' },
        { id: 'black', label: 'Washed Black', value: '#1c1c1c' },
      ]),
      sizeVariant(['28', '30', '32', '34', '36'], ['28']),
    ],
  },
  {
    id: 'p15',
    slug: 'voyager-commuter-backpack',
    name: 'Voyager Commuter Backpack',
    brand: 'Onyx',
    category: 'accessories',
    price: 158,
    oldPrice: 195,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 429,
    images: ['/images/p-backpack.png'],
    colors: ['#3a3733', '#1c1c1c'],
    badge: '19% OFF',
    inStock: true,
    stockCount: 17,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'A water-resistant canvas and leather commuter backpack with a padded laptop compartment and hidden pockets.',
    highlights: ['Water-resistant canvas', 'Fits 16" laptop', 'Luggage pass-through', 'Hidden security pocket'],
    specifications: [
      { label: 'Material', value: 'Canvas & leather' },
      { label: 'Capacity', value: '22L' },
      { label: 'Laptop', value: 'Up to 16"' },
    ],
  },
  {
    id: 'p16',
    slug: 'pulse-fitness-smartwatch',
    name: 'Pulse Fitness Smartwatch',
    brand: 'Auralis',
    category: 'tech',
    price: 249,
    oldPrice: 299,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 967,
    images: ['/images/p-smartwatch.png'],
    colors: ['#1c1c1c', '#e6e1d8'],
    badge: '17% OFF',
    inStock: true,
    stockCount: 26,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'Track workouts, sleep, and heart rate with a bright always-on display and up to 10-day battery life.',
    highlights: ['Always-on AMOLED', 'GPS & heart rate', '10-day battery', '50m water resistance'],
    specifications: [
      { label: 'Display', value: '1.4" AMOLED' },
      { label: 'Battery', value: 'Up to 10 days' },
      { label: 'Sensors', value: 'GPS, HR, SpO2' },
      { label: 'Water', value: '50m' },
    ],
    variants: [
      colorVariant([
        { id: 'black', label: 'Graphite', value: '#1c1c1c' },
        { id: 'ivory', label: 'Ivory', value: '#e6e1d8' },
      ]),
    ],
  },
  {
    id: 'p17',
    slug: 'halo-led-desk-lamp',
    name: 'Halo LED Desk Lamp',
    brand: 'Lumen',
    category: 'home',
    price: 96,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 288,
    images: ['/images/p-lamp.png'],
    colors: ['#1c1c1c', '#e6e1d8'],
    badge: 'New',
    inStock: true,
    stockCount: 33,
    freeDelivery: true,
    isNew: true,
    description:
      'A minimalist LED desk lamp with stepless dimming, adjustable color temperature, and a USB-C charging port.',
    highlights: ['Stepless dimming', 'Adjustable warmth', 'Built-in USB-C', 'Flicker-free light'],
    specifications: [
      { label: 'Light', value: 'LED, flicker-free' },
      { label: 'Temp', value: '2700K–6500K' },
      { label: 'Port', value: 'USB-C 18W' },
    ],
    variants: [
      colorVariant([
        { id: 'black', label: 'Matte Black', value: '#1c1c1c' },
        { id: 'ivory', label: 'Ivory', value: '#e6e1d8' },
      ]),
    ],
  },
  {
    id: 'p18',
    slug: 'noir-eau-de-parfum',
    name: 'Noir Eau de Parfum',
    brand: 'Maison Vela',
    category: 'beauty',
    price: 128,
    oldPrice: 150,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 721,
    images: ['/images/p-perfume.png'],
    badge: '15% OFF',
    inStock: true,
    stockCount: 19,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'A warm, sophisticated eau de parfum with notes of amber, oud, and bergamot for lasting all-day wear.',
    highlights: ['Amber & oud', '50ml', 'Long-lasting', 'Cruelty-free'],
    specifications: [
      { label: 'Volume', value: '50ml' },
      { label: 'Family', value: 'Amber woody' },
      { label: 'Longevity', value: '8+ hours' },
    ],
  },
  {
    id: 'p19',
    slug: 'ridge-suede-chelsea-boots',
    name: 'Ridge Suede Chelsea Boots',
    brand: 'Northwood',
    category: 'footwear',
    price: 228,
    oldPrice: 280,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 356,
    images: ['/images/p-boots.png'],
    colors: ['#a97d4f', '#3a3733'],
    badge: 'Best Seller',
    inStock: true,
    stockCount: 13,
    freeDelivery: true,
    isBestSeller: true,
    description:
      'Handcrafted suede chelsea boots with elastic side panels and a durable, comfortable crepe sole.',
    highlights: ['Premium suede', 'Elastic side panels', 'Crepe sole', 'Goodyear welted'],
    specifications: [
      { label: 'Upper', value: 'Suede' },
      { label: 'Sole', value: 'Crepe rubber' },
      { label: 'Construction', value: 'Goodyear welt' },
    ],
    variants: [
      colorVariant([
        { id: 'tan', label: 'Tan', value: '#a97d4f' },
        { id: 'charcoal', label: 'Charcoal', value: '#3a3733' },
      ]),
      sizeVariant(['6', '7', '8', '9', '10', '11', '12'], ['6']),
    ],
  },
  {
    id: 'p20',
    slug: 'aria-silk-scarf',
    name: 'Aria Silk Scarf',
    brand: 'Maison Vela',
    category: 'accessories',
    price: 95,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 174,
    images: ['/images/p-scarf.png'],
    colors: ['#d8cdba', '#c8a98a'],
    badge: 'New',
    inStock: true,
    stockCount: 28,
    freeDelivery: false,
    isNew: true,
    description:
      'A luxuriously soft mulberry silk scarf with a hand-rolled edge and an elegant printed motif.',
    highlights: ['100% mulberry silk', 'Hand-rolled edge', 'Printed motif', '90 x 90cm'],
    specifications: [
      { label: 'Material', value: '100% silk' },
      { label: 'Size', value: '90 x 90cm' },
      { label: 'Edge', value: 'Hand-rolled' },
    ],
  },
  {
    id: 'p21',
    slug: 'aeon-studio-monitor',
    name: 'Aeon Studio Monitor Speaker',
    brand: 'Auralis',
    category: 'tech',
    price: 399,
    oldPrice: 469,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 213,
    images: ['/images/p-speaker.png', '/images/p-headphones.png'],
    colors: ['#1c1c1c', '#e6e1d8'],
    badge: 'Luxury',
    inStock: true,
    stockCount: 7,
    freeDelivery: true,
    description:
      'A reference-grade powered studio monitor with a woven driver and precision-tuned bass port for accurate sound.',
    highlights: ['Reference-grade audio', 'Woven driver', 'Bi-amplified', 'Balanced inputs'],
    specifications: [
      { label: 'Power', value: '120W bi-amp' },
      { label: 'Driver', value: '5" woven cone' },
      { label: 'Inputs', value: 'XLR / TRS' },
    ],
  },
  {
    id: 'p22',
    slug: 'terra-linen-throw',
    name: 'Terra Linen Throw Blanket',
    brand: 'Terra&Co',
    category: 'home',
    price: 78,
    oldPrice: 98,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 341,
    images: ['/images/p-candle.png', '/images/cat-home.png'],
    colors: ['#d8cdba', '#c8a98a'],
    badge: '20% OFF',
    inStock: true,
    stockCount: 35,
    freeDelivery: false,
    description:
      'A stonewashed pure linen throw with tasseled edges that softens beautifully with every wash.',
    highlights: ['100% stonewashed linen', 'Tasseled edges', '130 x 170cm', 'Oeko-Tex certified'],
    specifications: [
      { label: 'Material', value: '100% linen' },
      { label: 'Size', value: '130 x 170cm' },
      { label: 'Care', value: 'Machine washable' },
    ],
  },
  {
    id: 'p23',
    slug: 'lumen-daily-moisturizer',
    name: 'Lumen Daily Moisturizer',
    brand: 'Lumen',
    category: 'beauty',
    price: 46,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 889,
    images: ['/images/p-serum.png'],
    inStock: true,
    stockCount: 42,
    freeDelivery: true,
    description:
      'A lightweight daily moisturizer with ceramides and niacinamide that hydrates without a greasy finish.',
    highlights: ['Ceramides & niacinamide', 'Non-greasy', 'Fragrance-free', 'SPF 30'],
    specifications: [
      { label: 'Volume', value: '50ml' },
      { label: 'SPF', value: '30' },
      { label: 'Skin type', value: 'All types' },
    ],
  },
  {
    id: 'p24',
    slug: 'onyx-titanium-sunglasses',
    name: 'Onyx Titanium Sunglasses',
    brand: 'Onyx',
    category: 'accessories',
    price: 189,
    oldPrice: 230,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 158,
    images: ['/images/p-sunglasses.png'],
    colors: ['#1c1c1c', '#c8a98a'],
    badge: '18% OFF',
    inStock: false,
    stockCount: 0,
    freeDelivery: true,
    description:
      'Ultra-light titanium aviators with polarized gradient lenses and adjustable nose pads for a perfect fit.',
    highlights: ['Titanium frame', 'Polarized gradient lenses', 'Adjustable nose pads', 'UV400'],
    specifications: [
      { label: 'Frame', value: 'Titanium' },
      { label: 'Lens', value: 'Polarized UV400' },
      { label: 'Weight', value: '18g' },
    ],
  },
]

// attach reviews to each product
products.forEach((p) => {
  p.reviews = sampleReviews(p.name)
})

export const heroSlides: HeroSlide[] = [
  {
    id: 'h1',
    eyebrow: 'Autumn Collection 2026',
    title: 'Elevated essentials for everyday life',
    subtitle: 'Discover curated pieces designed to move with you — crafted to last, styled to love.',
    image: '/images/hero-fashion.png',
    ctaLabel: 'Shop the collection',
    ctaHref: '/category/fashion',
    align: 'left',
    theme: 'dark',
  },
  {
    id: 'h2',
    eyebrow: 'Sound, reimagined',
    title: 'Technology that disappears into your day',
    subtitle: 'Immersive audio and considered design. Meet the new Aeon lineup.',
    image: '/images/hero-tech.png',
    ctaLabel: 'Explore tech',
    ctaHref: '/category/tech',
    align: 'left',
    theme: 'dark',
  },
  {
    id: 'h3',
    eyebrow: 'The Home Edit',
    title: 'Objects that make a house a home',
    subtitle: 'Warm materials, honest craft, and pieces you’ll keep for a lifetime.',
    image: '/images/hero-home.png',
    ctaLabel: 'Shop home',
    ctaHref: '/category/home',
    align: 'left',
    theme: 'dark',
  },
]

export const collections: Collection[] = [
  {
    id: 'col1',
    title: 'The Luxury Edit',
    subtitle: 'Investment pieces worth the wait',
    image: '/images/cat-accessories.png',
    href: '/category/accessories',
    size: 'wide',
  },
  {
    id: 'col2',
    title: 'Fresh Beauty',
    subtitle: 'Rituals for radiant skin',
    image: '/images/cat-beauty.png',
    href: '/category/beauty',
    size: 'normal',
  },
  {
    id: 'col3',
    title: 'Sound & Vision',
    subtitle: 'Tech that feels effortless',
    image: '/images/cat-tech.png',
    href: '/category/tech',
    size: 'normal',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    author: 'Sofia Marchetti',
    role: 'Verified buyer',
    quote:
      'SmartGO has completely changed how I shop online. The quality is consistently excellent and delivery is unbelievably fast.',
    rating: 5,
  },
  {
    id: 't2',
    author: 'James Okafor',
    role: 'Verified buyer',
    quote: 'Every order feels like unwrapping a gift. The packaging, the products, the little details — all considered.',
    rating: 5,
  },
  {
    id: 't3',
    author: 'Mei Lin',
    role: 'Verified buyer',
    quote: 'Finally a store that feels premium without the premium hassle. Returns are painless and support is superb.',
    rating: 5,
  },
]

export const trendingSearches: string[] = [
  'Wireless headphones',
  'Trench coat',
  'Leather tote',
  'Skincare serum',
  'Lounge chair',
  'Sneakers',
]

export const coupons: Coupon[] = [
  { code: 'WELCOME10', label: '10% off your first order', discountPct: 10 },
  { code: 'DIWALI20', label: '20% off orders over ₹15,000', discountPct: 20 },
]

export const banners = {
  announcements: [
    'Free delivery on orders over ₹999',
    'Members get early access to the Diwali drop',
    'Easy 30-day returns, always',
  ],
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(slug: string) {
  if (slug === 'all' || slug === 'sale' || slug === 'new-arrivals') return products
  return products.filter((p) => p.category === slug)
}

export function getRelatedProducts(product: Product, count = 4) {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, count)
}

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug)
}
